---
- name: install apache on ubuntu
  hosts: all
  become: true
  tasks:
  - name: install apache
    apt:
      name: apache2
      state: present
    notify: start apache2
    
  - name: Deploy static website
    copy:
      src: index.html
      dest: /var/www/html/

  handlers:
  - name: start apache2
    service:
      name: apache2
      state: started
